profile_manager_folder: ".wonderdraft_profile_manager"
#this will be created inside the main folder!
inactiveModulesFolder: "wonderdraft_profile_manager_INACTIVE"
#this will be created inside the main folder!
logging_folder: "wonderdraft_profile_manager_logs"